from .if_aras import ifARAS
from .if_codas import ifCODAS
from .if_copras import ifCOPRAS
from .if_edas import ifEDAS
from .if_mabac import ifMABAC
from .if_mairca import ifMAIRCA
from .if_moora import ifMOORA
from .if_topsis import ifTOPSIS
from .if_vikor import ifVIKOR
from .ifs import *
