from .if_aras import ifARAS
from .if_codas import ifCODAS
from .if_copras import ifCOPRAS
from .if_edas import ifEDAS
from .if_mabac import ifMABAC
from .if_mairca import ifMAIRCA
from .if_marcos import ifMARCOS
from .if_moora import ifMOORA
from .if_ocra import ifOCRA
from .if_topsis import ifTOPSIS
from .if_vikor import ifVIKOR
from .if_waspas import ifWASPAS
from .if_wpm import ifWPM
from .if_wsm import ifWSM
from .ifs import *
